# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: shopping-cart
spec:

  # Journal configuration
  journal:

    # Name of a deployed EventSourcedJournal to use.
    name: inmemory

  containers:
    - image: cloudstateio/js-shopping-cart:latest
