# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: EventSourcedService
metadata:
  name: shopping-cart
spec:

  # Journal configuration
  journal:

    # Name of a deployed EventSourcedJournal to use.
    name: cassandra

    # Journal specific configuration
    config:

      # Since the journal is a Cassandra journal, we need to specify the keyspace to use.
      keyspace: shoppingcart

  nodeSelector:
    loadtest: cloudstate

  tolerations:
  - key: loadtest
    value: cloudstate

  autoscaling:
    userFunctionTargetConcurrency: 5
    requestRateThresholdFactor: 2.0
    scaleDownStableDeadline: 1m

  containers:
    - image: gcr.io/stateserv/js-shopping-cart:latest
